import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { join, extname } from "node:path";
import test from "node:test";

/**
 * Recursively collect all .ts/.tsx source files under `dir`.
 * This is a pure-Node replacement for `rg -l <pattern> src --glob '*.ts' --glob '*.tsx'`.
 * Every divergence from ripgrep is in the STRICTER direction, so the contract can never be
 * silently weakened: it does NOT read .gitignore (it scans all non-node_modules dirs), and it
 * DOES scan dot-prefixed files (it only skips node_modules and dot-prefixed directories).
 */
async function collectSourceFiles(dir) {
  const results = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      results.push(...(await collectSourceFiles(fullPath)));
    } else if (entry.isFile() && [".ts", ".tsx"].includes(extname(entry.name))) {
      // entry.isFile() guard: avoids EISDIR from a directory literally named *.ts, and
      // excludes symlinks (Dirent reports isFile()=false for them), matching rg's default
      // of not following symlinks.
      results.push(fullPath);
    }
  }
  return results;
}

test("generated bindings have a deterministic warning header", async () => {
  const bindings = (await readFile("src/generated/bindings.ts", "utf8")).replace(
    /\r\n/g,
    "\n",
  );
  assert.ok(bindings.startsWith("// Generated by ts-rs. Do not edit.\n"));
  assert.match(bindings, /export type CommandResult<T>/);
  assert.match(bindings, /export type FoundationStatus/);
  assert.match(bindings, /export type PublicError/);
  assert.match(bindings, /export type SecretStatus/);
  assert.doesNotMatch(bindings, /secret(Value|Contents)|password/i);
  assert.match(bindings, /ProviderSaveInput = \{[^}]*apiKey: string \| null/);
  // LiveKit 传输已移除：bindings 不得再出现任何 LiveKit 类型。
  assert.doesNotMatch(bindings, /LiveKit/);
  for (const outputType of ["ProviderConfig", "PublicConfig", "ProviderTestResult", "ModelDiscoveryResult", "EmbeddingTestResult", "RoleProfileConfig"]) {
    const declaration = bindings.match(new RegExp(`export type ${outputType} = \\{[^;]+;`))?.[0] ?? "";
    assert.doesNotMatch(declaration, /apiKey: string|apiSecret: string|secret(Value|Contents)|password/i, `${outputType} must remain redacted`);
  }
});

test("only the command adapter imports the low-level Tauri invoke API", async () => {
  // Same contract the previous `rg -l` scan enforced: the set of PRODUCTION .ts/.tsx
  // files under src importing "@tauri-apps/api/core" must be exactly { src/api/commands.ts }.
  // Test doubles (*.test.*) legitimately mock the low-level invoke API and are exempt,
  // mirroring page-shell-contract's `.test.` exclusion; every production module is still scanned.
  const files = [];
  for (const file of await collectSourceFiles("src")) {
    const normalized = file.replaceAll("\\", "/");
    if (normalized.includes(".test.")) continue;
    const content = await readFile(file, "utf8");
    if (content.includes("@tauri-apps/api/core")) {
      files.push(normalized);
    }
  }
  files.sort();
  assert.deepEqual(files, ["src/api/commands.ts"]);
});
